#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(head -n 1 "$COMMIT_MSG_FILE")

# Regex for "DEXO-<number> - <Message>"
# We use bash's built in regular expression matching
REGEX="^DEXO-[0-9]+ - .+"

# Allow merge commits
if [[ "$COMMIT_MSG" =~ ^Merge.* ]]; then
    exit 0
fi

# Allow revert commits
if [[ "$COMMIT_MSG" =~ ^Revert.* ]]; then
    exit 0
fi

if [[ ! "$COMMIT_MSG" =~ $REGEX ]]; then
    echo "❌ Error: Invalid commit message format."
    echo "   Commit: '$COMMIT_MSG'"
    echo "   Required format: 'DEXO-<issue_number> - <Message>'"
    echo "   Example:         'DEXO-1 - Add new feature'"
    exit 1
fi
